version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_0707Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_0707.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GIT_0707Project
    version: "1.0"
- serviceName: project.siqa_git_0707.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GIT_0707Project
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: project.siqa_git_0707.integrations:Call_refData
  packages:
  - name: SIQA_GIT_0707Project
    version: "1.0"
- serviceName: project.siqa_git_0707.referencedata:refData
  packages:
  - name: SIQA_GIT_0707Project
    version: "1.0"
- serviceName: project.siqa_git_0707.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_0707Project
    version: "1.0"
- serviceName: project.siqa_git_0707.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_0707Project
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
